# This makefile is part of the demo for lecture 13_heap
# Note that this is not the best way to do a makefile, but
# more details is covered in a later lecture
main_queue: main_queue.c queue.c
	clang -o main_queue main_queue.c queue.c
